# Generated by Django 4.1.6 on 2023-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
