# Generated by Django 4.1.7 on 2023-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_nike', '0004_alter_nikeuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikeuser',
            name='password',
            field=models.TextField(),
        ),
    ]
