# Generated by Django 4.1.7 on 2023-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_nike', '0005_alter_nikeuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikeuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
