# Generated by Django 4.1.6 on 2023-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_nike', '0006_nikeuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nikeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nikeuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
