# Generated by Django 4.1.6 on 2023-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_nike', '0007_nikeuser_is_active_nikeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
