# Generated by Django 4.1.6 on 2023-07-30 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nike', '0002_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BucketModel',
            new_name='Bucket',
        ),
    ]
