# Generated by Django 4.1.6 on 2023-07-30 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nike', '0002_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_rename_bucketmodel_bucket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucket',
            new_name='Basket',
        ),
    ]
