# Generated by Django 4.1.6 on 2023-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_bucket_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
